defaults:
  - default
  - ../model@model: v1
  - _self_


training:
  learning_rate: 4e-4
  optim: "muon"

processor:
  beatmap_parser:
    add_snapping: false
    add_distances: false

  beatmap_tokenizer:
    position_split_axes: false
    add_cls_token: true
    separate_new_combo_token: false

  metadata_tokenizer:
    add_cls_token: true

model:
    metadata_config:
        cls_embed: true

    beatmap_config:
        cls_embed: true

dataset:
  min_year: 2007
  train_metadata_variations: 256